spring:
  application:
    name: coffee-api
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs